import { NextRequest, NextResponse } from "next/server";
import { getDb } from "@/lib/db";
import { requireAuth } from "@/lib/auth";

const DURATION_MINUTES: Record<string, number> = {
  easy: 30,
  medium: 45,
  hard: 60,
};

function pad2(n: number): string {
  return String(n).padStart(2, "0");
}

function toIcsDate(dateStr: string, timeStr: string | null): string {
  // dateStr = "YYYY-MM-DD", timeStr = "HH:MM" or null
  const [y, m, d] = dateStr.split("-");
  const [h, min] = (timeStr || "09:00").split(":");
  return `${y}${m}${d}T${h}${min}00`;
}

function addMinutes(icsDate: string, minutes: number): string {
  // Parse "YYYYMMDDTHHmmss" and add minutes
  const y = parseInt(icsDate.slice(0, 4));
  const m = parseInt(icsDate.slice(4, 6)) - 1;
  const d = parseInt(icsDate.slice(6, 8));
  const h = parseInt(icsDate.slice(9, 11));
  const min = parseInt(icsDate.slice(11, 13));
  const date = new Date(y, m, d, h, min);
  date.setMinutes(date.getMinutes() + minutes);
  return `${date.getFullYear()}${pad2(date.getMonth() + 1)}${pad2(date.getDate())}T${pad2(date.getHours())}${pad2(date.getMinutes())}00`;
}

function escapeIcs(text: string): string {
  return text.replace(/\\/g, "\\\\").replace(/;/g, "\\;").replace(/,/g, "\\,").replace(/\n/g, "\\n");
}

function generateUid(id: number): string {
  return `socraty-item-${id}@socraty.ai`;
}

interface CalendarItem {
  id: number;
  title: string;
  description: string;
  difficulty: string;
  topic: string | null;
  scheduled_date: string;
  scheduled_time: string | null;
}

export async function GET(req: NextRequest) {
  const user = await requireAuth(req);
  if (!user) {
    return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
  }

  const itemId = req.nextUrl.searchParams.get("itemId");
  const date = req.nextUrl.searchParams.get("date");
  const start = req.nextUrl.searchParams.get("start");
  const end = req.nextUrl.searchParams.get("end");

  const db = getDb();
  let items: CalendarItem[];

  if (itemId) {
    items = await db.all(
      `SELECT ai.id, ai.title, ai.description, ai.difficulty, ai.topic,
              ai.scheduled_date, ai.scheduled_time
       FROM action_items ai
       JOIN files f ON f.id = ai.file_id AND f.user_id = ?
       WHERE ai.id = ? AND ai.scheduled_date IS NOT NULL`,
      user.id, Number(itemId)
    ) as CalendarItem[];
  } else if (date) {
    items = await db.all(
      `SELECT ai.id, ai.title, ai.description, ai.difficulty, ai.topic,
              ai.scheduled_date, ai.scheduled_time
       FROM action_items ai
       JOIN files f ON f.id = ai.file_id AND f.user_id = ?
       WHERE ai.scheduled_date = ?
       ORDER BY ai.scheduled_time, ai.difficulty`,
      user.id, date
    ) as CalendarItem[];
  } else if (start && end) {
    items = await db.all(
      `SELECT ai.id, ai.title, ai.description, ai.difficulty, ai.topic,
              ai.scheduled_date, ai.scheduled_time
       FROM action_items ai
       JOIN files f ON f.id = ai.file_id AND f.user_id = ?
       WHERE ai.scheduled_date BETWEEN ? AND ?
       ORDER BY ai.scheduled_date, ai.scheduled_time, ai.difficulty`,
      user.id, start, end
    ) as CalendarItem[];
  } else {
    return NextResponse.json({ error: "Provide itemId, date, or start+end" }, { status: 400 });
  }

  if (items.length === 0) {
    return NextResponse.json({ error: "No scheduled items found" }, { status: 404 });
  }

  // Build ICS
  const events = items.map((item) => {
    const dtStart = toIcsDate(item.scheduled_date, item.scheduled_time);
    const duration = DURATION_MINUTES[item.difficulty] || 30;
    const dtEnd = addMinutes(dtStart, duration);
    const diffLabel = item.difficulty === "easy" ? "Foundations" : item.difficulty === "medium" ? "Solidification" : "Mastery";
    const desc = [
      item.description,
      item.topic ? `Topic: ${item.topic}` : "",
      `Difficulty: ${diffLabel}`,
      "Generated by Socraty AI",
    ]
      .filter(Boolean)
      .join("\\n");

    return [
      "BEGIN:VEVENT",
      `UID:${generateUid(item.id)}`,
      `DTSTART:${dtStart}`,
      `DTEND:${dtEnd}`,
      `SUMMARY:${escapeIcs(`[${diffLabel}] ${item.title}`)}`,
      `DESCRIPTION:${escapeIcs(desc)}`,
      "END:VEVENT",
    ].join("\r\n");
  });

  const ics = [
    "BEGIN:VCALENDAR",
    "VERSION:2.0",
    "PRODID:-//Socraty AI//Calendar//EN",
    "CALSCALE:GREGORIAN",
    "METHOD:PUBLISH",
    ...events,
    "END:VCALENDAR",
  ].join("\r\n");

  const filename = itemId
    ? `study-item-${itemId}.ics`
    : date
    ? `study-${date}.ics`
    : `study-${start}-to-${end}.ics`;

  return new NextResponse(ics, {
    headers: {
      "Content-Type": "text/calendar; charset=utf-8",
      "Content-Disposition": `attachment; filename="${filename}"`,
    },
  });
}
