"use client";

import { useState, useEffect, useCallback, useMemo, useRef } from "react";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { toast } from "sonner";
import type { ActionItem } from "@/types";
import type { CalendarSettings, DayAvailability } from "@/lib/calendar-settings";

type ViewMode = "week" | "month";

const DIFFICULTY_COLORS: Record<string, { dot: string; bg: string; text: string }> = {
  easy: { dot: "bg-emerald-500", bg: "bg-emerald-50 dark:bg-emerald-950", text: "text-emerald-700 dark:text-emerald-300" },
  medium: { dot: "bg-amber-500", bg: "bg-amber-50 dark:bg-amber-950", text: "text-amber-700 dark:text-amber-300" },
  hard: { dot: "bg-red-500", bg: "bg-red-50 dark:bg-red-950", text: "text-red-700 dark:text-red-300" },
};

const DAY_NAMES = ["Mon", "Tue", "Wed", "Thu", "Fri", "Sat", "Sun"];
const DAY_KEYS = ["monday", "tuesday", "wednesday", "thursday", "friday", "saturday", "sunday"];
const MONTH_NAMES = [
  "January", "February", "March", "April", "May", "June",
  "July", "August", "September", "October", "November", "December",
];

const COMMON_TIMEZONES = [
  "America/New_York", "America/Chicago", "America/Denver", "America/Los_Angeles",
  "America/Toronto", "America/Sao_Paulo", "Europe/London", "Europe/Paris",
  "Europe/Berlin", "Europe/Istanbul", "Asia/Dubai", "Asia/Kolkata",
  "Asia/Singapore", "Asia/Tokyo", "Asia/Shanghai", "Australia/Sydney",
  "Pacific/Auckland",
];

const DURATION_MINUTES: Record<string, number> = { easy: 30, medium: 45, hard: 60 };

function formatTime12h(time: string): string {
  if (!time) return "";
  const [h, m] = time.split(":").map(Number);
  const period = h >= 12 ? "PM" : "AM";
  const h12 = h === 0 ? 12 : h > 12 ? h - 12 : h;
  return `${h12}:${String(m).padStart(2, "0")} ${period}`;
}

function buildGoogleCalUrl(item: ActionItem): string {
  const date = (item.scheduled_date || "").replace(/-/g, "");
  const time = (item.scheduled_time || "09:00").replace(":", "");
  const dtStart = `${date}T${time}00`;
  // Calculate end time
  const dur = DURATION_MINUTES[item.difficulty] || 30;
  const startDate = new Date(
    parseInt(date.slice(0, 4)), parseInt(date.slice(4, 6)) - 1, parseInt(date.slice(6, 8)),
    parseInt(time.slice(0, 2)), parseInt(time.slice(2, 4))
  );
  startDate.setMinutes(startDate.getMinutes() + dur);
  const dtEnd = `${startDate.getFullYear()}${String(startDate.getMonth() + 1).padStart(2, "0")}${String(startDate.getDate()).padStart(2, "0")}T${String(startDate.getHours()).padStart(2, "0")}${String(startDate.getMinutes()).padStart(2, "0")}00`;
  const diffLabel = item.difficulty === "easy" ? "Foundations" : item.difficulty === "medium" ? "Solidification" : "Mastery";
  const title = `[${diffLabel}] ${item.title}`;
  const details = [item.description, item.topic ? `Topic: ${item.topic}` : "", "Generated by Socraty AI"].filter(Boolean).join("\n");
  const params = new URLSearchParams({
    action: "TEMPLATE",
    text: title,
    dates: `${dtStart}/${dtEnd}`,
    details,
  });
  return `https://calendar.google.com/calendar/render?${params.toString()}`;
}

function toDateStr(d: Date): string {
  const y = d.getFullYear();
  const m = String(d.getMonth() + 1).padStart(2, "0");
  const day = String(d.getDate()).padStart(2, "0");
  return `${y}-${m}-${day}`;
}

function getMonday(d: Date): Date {
  const date = new Date(d);
  const day = date.getDay();
  const diff = day === 0 ? -6 : 1 - day;
  date.setDate(date.getDate() + diff);
  return date;
}

function addDays(d: Date, n: number): Date {
  const date = new Date(d);
  date.setDate(date.getDate() + n);
  return date;
}

function getWeekRange(anchor: Date): { start: Date; end: Date } {
  const monday = getMonday(anchor);
  const sunday = addDays(monday, 6);
  return { start: monday, end: sunday };
}

function getMonthRange(anchor: Date): { start: Date; end: Date } {
  const firstOfMonth = new Date(anchor.getFullYear(), anchor.getMonth(), 1);
  const lastOfMonth = new Date(anchor.getFullYear(), anchor.getMonth() + 1, 0);
  const start = getMonday(firstOfMonth);
  const endDay = lastOfMonth.getDay();
  const end = endDay === 0 ? lastOfMonth : addDays(lastOfMonth, 7 - endDay);
  return { start, end };
}

export function CalendarTab() {
  const [viewMode, setViewMode] = useState<ViewMode>("week");
  const [anchor, setAnchor] = useState(() => new Date());
  const [items, setItems] = useState<ActionItem[]>([]);
  const [isAutoPushing, setIsAutoPushing] = useState(false);
  const [selectedDate, setSelectedDate] = useState<string | null>(null);
  const [loading, setLoading] = useState(false);
  const [showSettings, setShowSettings] = useState(false);

  const todayStr = useMemo(() => toDateStr(new Date()), []);

  const range = useMemo(() => {
    return viewMode === "week" ? getWeekRange(anchor) : getMonthRange(anchor);
  }, [viewMode, anchor]);

  const fetchItems = useCallback(async () => {
    setLoading(true);
    try {
      const start = toDateStr(range.start);
      const end = toDateStr(range.end);
      const res = await fetch(`/api/calendar?start=${start}&end=${end}`);
      const data = await res.json();
      setItems(data.items ?? []);
    } catch {
      // silent
    } finally {
      setLoading(false);
    }
  }, [range]);

  useEffect(() => {
    fetchItems();
  }, [fetchItems]);

  const handleAutoPush = useCallback(async () => {
    setIsAutoPushing(true);
    try {
      const res = await fetch("/api/calendar/auto-push", { method: "POST" });
      const data = await res.json();
      if (!res.ok) throw new Error(data.error || "Auto Push failed");
      if (data.scheduled === 0) {
        toast.info("No unscheduled items to push");
      } else {
        toast.success(`Scheduled ${data.scheduled} items across your calendar`);
      }
      fetchItems();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Auto Push failed");
    } finally {
      setIsAutoPushing(false);
    }
  }, [fetchItems]);

  const handleToggleComplete = useCallback(async (id: number, completed: boolean) => {
    try {
      await fetch("/api/action-items", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, completed }),
      });
      setItems((prev) =>
        prev.map((item) =>
          item.id === id
            ? { ...item, completed: completed ? 1 : 0, completed_at: completed ? new Date().toISOString() : null }
            : item
        )
      );
    } catch {
      toast.error("Failed to update item");
    }
  }, []);

  const handleReschedule = useCallback(async (id: number, scheduled_date: string | null, scheduled_time?: string | null) => {
    try {
      await fetch("/api/calendar/reschedule", {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ id, scheduled_date, scheduled_time }),
      });
      fetchItems();
      toast.success(scheduled_date ? "Item rescheduled" : "Item unscheduled");
    } catch {
      toast.error("Failed to reschedule");
    }
  }, [fetchItems]);

  const navigate = (direction: -1 | 1) => {
    setAnchor((prev) => {
      const d = new Date(prev);
      if (viewMode === "week") {
        d.setDate(d.getDate() + direction * 7);
      } else {
        d.setMonth(d.getMonth() + direction);
      }
      return d;
    });
    setSelectedDate(null);
  };

  const goToday = () => {
    setAnchor(new Date());
    setSelectedDate(null);
  };

  // Group items by date, sorted by time within each day
  const itemsByDate = useMemo(() => {
    const map: Record<string, ActionItem[]> = {};
    for (const item of items) {
      if (item.scheduled_date) {
        if (!map[item.scheduled_date]) map[item.scheduled_date] = [];
        map[item.scheduled_date].push(item);
      }
    }
    // Sort each day's items by scheduled_time
    for (const dateStr of Object.keys(map)) {
      map[dateStr].sort((a, b) => {
        if (a.scheduled_time && b.scheduled_time) return a.scheduled_time.localeCompare(b.scheduled_time);
        if (a.scheduled_time) return -1;
        if (b.scheduled_time) return 1;
        return 0;
      });
    }
    return map;
  }, [items]);

  // Generate days for current view
  const days = useMemo(() => {
    const result: Date[] = [];
    let current = new Date(range.start);
    while (current <= range.end) {
      result.push(new Date(current));
      current = addDays(current, 1);
    }
    return result;
  }, [range]);

  const headerLabel = viewMode === "week"
    ? `${range.start.toLocaleDateString("en-US", { month: "short", day: "numeric" })} - ${range.end.toLocaleDateString("en-US", { month: "short", day: "numeric", year: "numeric" })}`
    : `${MONTH_NAMES[anchor.getMonth()]} ${anchor.getFullYear()}`;

  const selectedItems = selectedDate ? itemsByDate[selectedDate] ?? [] : [];

  if (showSettings) {
    return <CalendarSettingsPanel onClose={() => setShowSettings(false)} />;
  }

  return (
    <div className="space-y-4">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center gap-3">
          {/* View toggle */}
          <div className="flex items-center gap-1 p-1 bg-muted rounded-lg">
            {(["week", "month"] as ViewMode[]).map((mode) => (
              <button
                key={mode}
                onClick={() => { setViewMode(mode); setSelectedDate(null); }}
                className={`px-3 py-1.5 rounded-md text-xs font-medium transition-all ${
                  viewMode === mode
                    ? "bg-background shadow-sm text-foreground"
                    : "text-muted-foreground hover:text-foreground"
                }`}
              >
                {mode === "week" ? "Week" : "Month"}
              </button>
            ))}
          </div>

          {/* Navigation */}
          <div className="flex items-center gap-1">
            <button
              onClick={() => navigate(-1)}
              className="p-1.5 rounded-lg text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
              </svg>
            </button>
            <button
              onClick={() => navigate(1)}
              className="p-1.5 rounded-lg text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
            >
              <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M9 5l7 7-7 7" />
              </svg>
            </button>
          </div>

          <h2 className="text-lg font-semibold">{headerLabel}</h2>

          <button
            onClick={goToday}
            className="px-3 py-1 rounded-lg text-xs font-medium border border-border hover:bg-muted transition-colors"
          >
            Today
          </button>
        </div>

        <div className="flex items-center gap-2">
          {/* Settings gear */}
          <button
            onClick={() => setShowSettings(true)}
            className="p-2 rounded-lg text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
            title="Calendar Settings"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M10.325 4.317c.426-1.756 2.924-1.756 3.35 0a1.724 1.724 0 002.573 1.066c1.543-.94 3.31.826 2.37 2.37a1.724 1.724 0 001.066 2.573c1.756.426 1.756 2.924 0 3.35a1.724 1.724 0 00-1.066 2.573c.94 1.543-.826 3.31-2.37 2.37a1.724 1.724 0 00-2.573 1.066c-.426 1.756-2.924 1.756-3.35 0a1.724 1.724 0 00-2.573-1.066c-1.543.94-3.31-.826-2.37-2.37a1.724 1.724 0 00-1.066-2.573c-1.756-.426-1.756-2.924 0-3.35a1.724 1.724 0 001.066-2.573c-.94-1.543.826-3.31 2.37-2.37.996.608 2.296.07 2.572-1.065z" />
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 12a3 3 0 11-6 0 3 3 0 016 0z" />
            </svg>
          </button>

          {/* Add to Calendar dropdown */}
          <AddToCalendarDropdown
            viewMode={viewMode}
            range={range}
            anchor={anchor}
            items={items}
          />

          {/* Auto Push */}
          <Button
            onClick={handleAutoPush}
            disabled={isAutoPushing}
            className="rounded-lg"
          >
            {isAutoPushing ? (
              <>
                <svg className="w-4 h-4 mr-2 animate-spin" fill="none" viewBox="0 0 24 24">
                  <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
                  <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
                </svg>
                Scheduling...
              </>
            ) : (
              <>
                <svg className="w-4 h-4 mr-2" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M13 10V3L4 14h7v7l9-11h-7z" />
                </svg>
                Auto Push
              </>
            )}
          </Button>
        </div>
      </div>

      {/* Calendar grid */}
      <div className="flex gap-4">
        <div className="flex-1 min-w-0">
          {viewMode === "week" ? (
            <WeekView
              days={days}
              todayStr={todayStr}
              itemsByDate={itemsByDate}
              selectedDate={selectedDate}
              onSelectDate={setSelectedDate}
              loading={loading}
            />
          ) : (
            <MonthView
              days={days}
              anchor={anchor}
              todayStr={todayStr}
              itemsByDate={itemsByDate}
              selectedDate={selectedDate}
              onSelectDate={setSelectedDate}
            />
          )}
        </div>

        {/* Day detail panel */}
        {selectedDate && (
          <DayDetail
            date={selectedDate}
            items={selectedItems}
            onClose={() => setSelectedDate(null)}
            onToggleComplete={handleToggleComplete}
            onReschedule={handleReschedule}
          />
        )}
      </div>
    </div>
  );
}

// --- Add to Calendar Dropdown ---

function AddToCalendarDropdown({
  viewMode,
  range,
  anchor,
  items,
}: {
  viewMode: ViewMode;
  range: { start: Date; end: Date };
  anchor: Date;
  items: ActionItem[];
}) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, []);

  const downloadIcs = (start: string, end: string) => {
    window.open(`/api/calendar/ics?start=${start}&end=${end}`, "_blank");
    setOpen(false);
  };

  const weekStart = toDateStr(getMonday(anchor));
  const weekEnd = toDateStr(addDays(getMonday(anchor), 6));
  const monthStart = toDateStr(new Date(anchor.getFullYear(), anchor.getMonth(), 1));
  const monthEnd = toDateStr(new Date(anchor.getFullYear(), anchor.getMonth() + 1, 0));

  if (items.length === 0) return null;

  return (
    <div className="relative" ref={ref}>
      <Button
        variant="outline"
        size="sm"
        onClick={() => setOpen(!open)}
        className="rounded-lg"
      >
        <svg className="w-4 h-4 mr-1.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
        Add to Calendar
        <svg className={`w-3 h-3 ml-1 transition-transform ${open ? "rotate-180" : ""}`} fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M19 9l-7 7-7-7" />
        </svg>
      </Button>
      {open && (
        <div className="absolute right-0 top-full mt-1 w-56 py-1 rounded-lg border border-border bg-popover shadow-lg z-20">
          <button
            onClick={() => downloadIcs(weekStart, weekEnd)}
            className="w-full flex items-center gap-2 px-3 py-2 text-sm text-popover-foreground hover:bg-accent transition-colors"
          >
            <svg className="w-4 h-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download This Week (.ics)
          </button>
          <button
            onClick={() => downloadIcs(monthStart, monthEnd)}
            className="w-full flex items-center gap-2 px-3 py-2 text-sm text-popover-foreground hover:bg-accent transition-colors"
          >
            <svg className="w-4 h-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download This Month (.ics)
          </button>
          <div className="border-t border-border my-1" />
          <button
            onClick={() => downloadIcs(toDateStr(range.start), toDateStr(range.end))}
            className="w-full flex items-center gap-2 px-3 py-2 text-sm text-popover-foreground hover:bg-accent transition-colors"
          >
            <svg className="w-4 h-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download Current {viewMode === "week" ? "Week" : "Month"} View
          </button>
        </div>
      )}
    </div>
  );
}

// --- Item Calendar Export Actions ---

function ItemCalendarActions({ item }: { item: ActionItem }) {
  const [open, setOpen] = useState(false);
  const ref = useRef<HTMLDivElement>(null);

  useEffect(() => {
    function handleClick(e: MouseEvent) {
      if (ref.current && !ref.current.contains(e.target as Node)) setOpen(false);
    }
    document.addEventListener("mousedown", handleClick);
    return () => document.removeEventListener("mousedown", handleClick);
  }, []);

  return (
    <div className="relative" ref={ref}>
      <button
        onClick={() => setOpen(!open)}
        className="p-1 rounded-md text-muted-foreground hover:text-primary hover:bg-primary/10 transition-colors"
        title="Add to calendar"
      >
        <svg className="w-3.5 h-3.5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M8 7V3m8 4V3m-9 8h10M5 21h14a2 2 0 002-2V7a2 2 0 00-2-2H5a2 2 0 00-2 2v12a2 2 0 002 2z" />
        </svg>
      </button>
      {open && (
        <div className="absolute right-0 bottom-full mb-1 w-48 py-1 rounded-lg border border-border bg-popover shadow-lg z-20">
          <button
            onClick={() => {
              window.open(buildGoogleCalUrl(item), "_blank");
              setOpen(false);
            }}
            className="w-full flex items-center gap-2 px-3 py-2 text-sm text-popover-foreground hover:bg-accent transition-colors"
          >
            <svg className="w-4 h-4" viewBox="0 0 24 24" fill="none">
              <rect x="2" y="3" width="20" height="18" rx="2" stroke="currentColor" strokeWidth="1.5" />
              <path d="M8 2v3M16 2v3M2 8h20" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" />
              <path d="M9 13l2 2 4-4" stroke="currentColor" strokeWidth="1.5" strokeLinecap="round" strokeLinejoin="round" />
            </svg>
            Google Calendar
          </button>
          <button
            onClick={() => {
              window.open(`/api/calendar/ics?itemId=${item.id}`, "_blank");
              setOpen(false);
            }}
            className="w-full flex items-center gap-2 px-3 py-2 text-sm text-popover-foreground hover:bg-accent transition-colors"
          >
            <svg className="w-4 h-4 text-muted-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
            </svg>
            Download .ics
          </button>
        </div>
      )}
    </div>
  );
}

// --- Calendar Settings Panel ---

function CalendarSettingsPanel({ onClose }: { onClose: () => void }) {
  const [settings, setSettings] = useState<CalendarSettings | null>(null);
  const [saving, setSaving] = useState(false);
  const [loadingSettings, setLoadingSettings] = useState(true);

  useEffect(() => {
    fetch("/api/calendar/settings")
      .then((r) => r.json())
      .then((data) => setSettings(data))
      .catch(() => toast.error("Failed to load settings"))
      .finally(() => setLoadingSettings(false));
  }, []);

  const handleSave = async () => {
    if (!settings) return;
    setSaving(true);
    try {
      const res = await fetch("/api/calendar/settings", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(settings),
      });
      if (!res.ok) {
        const data = await res.json();
        throw new Error(data.error || "Failed to save");
      }
      toast.success("Calendar settings saved");
      onClose();
    } catch (err) {
      toast.error(err instanceof Error ? err.message : "Failed to save settings");
    } finally {
      setSaving(false);
    }
  };

  const updateAvailability = (day: string, field: keyof DayAvailability, value: string | boolean) => {
    if (!settings) return;
    setSettings({
      ...settings,
      availability: {
        ...settings.availability,
        [day]: { ...settings.availability[day], [field]: value },
      },
    });
  };

  if (loadingSettings) {
    return (
      <div className="flex items-center justify-center py-20">
        <svg className="w-6 h-6 animate-spin text-muted-foreground" fill="none" viewBox="0 0 24 24">
          <circle className="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" strokeWidth="4" />
          <path className="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4z" />
        </svg>
      </div>
    );
  }

  if (!settings) return null;

  return (
    <div className="max-w-2xl">
      <div className="flex items-center justify-between mb-6">
        <div className="flex items-center gap-3">
          <button
            onClick={onClose}
            className="p-1.5 rounded-lg text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
          >
            <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M15 19l-7-7 7-7" />
            </svg>
          </button>
          <h2 className="text-lg font-semibold">Calendar Settings</h2>
        </div>
        <Button onClick={handleSave} disabled={saving} className="rounded-lg">
          {saving ? "Saving..." : "Save Settings"}
        </Button>
      </div>

      <div className="space-y-6">
        {/* Timezone */}
        <Card>
          <CardContent className="p-4">
            <label className="block text-sm font-medium mb-2">Timezone</label>
            <select
              value={settings.timezone}
              onChange={(e) => setSettings({ ...settings, timezone: e.target.value })}
              className="w-full rounded-lg border border-border bg-background px-3 py-2 text-sm focus:outline-none focus:ring-2 focus:ring-primary/20"
            >
              {COMMON_TIMEZONES.map((tz) => (
                <option key={tz} value={tz}>{tz.replace(/_/g, " ")}</option>
              ))}
            </select>
            <p className="text-xs text-muted-foreground mt-1">
              Action items will be scheduled in this timezone
            </p>
          </CardContent>
        </Card>

        {/* Items per day */}
        <Card>
          <CardContent className="p-4">
            <label className="block text-sm font-medium mb-2">
              Maximum items per day: <span className="text-primary">{settings.items_per_day}</span>
            </label>
            <input
              type="range"
              min={1}
              max={15}
              value={settings.items_per_day}
              onChange={(e) => setSettings({ ...settings, items_per_day: Number(e.target.value) })}
              className="w-full accent-primary"
            />
            <div className="flex justify-between text-[10px] text-muted-foreground mt-1">
              <span>Light (1)</span>
              <span>Default (6)</span>
              <span>Intensive (15)</span>
            </div>
          </CardContent>
        </Card>

        {/* Weekly availability */}
        <Card>
          <CardContent className="p-4">
            <label className="block text-sm font-medium mb-3">Weekly Availability</label>
            <div className="space-y-2">
              {DAY_KEYS.map((day, i) => {
                const config = settings.availability[day];
                if (!config) return null;
                return (
                  <div
                    key={day}
                    className={`flex items-center gap-3 p-3 rounded-lg border transition-colors ${
                      config.enabled ? "border-border bg-card" : "border-border/50 bg-muted/30"
                    }`}
                  >
                    {/* Toggle */}
                    <button
                      onClick={() => updateAvailability(day, "enabled", !config.enabled)}
                      className={`w-10 h-5 rounded-full relative transition-colors shrink-0 ${
                        config.enabled ? "bg-primary" : "bg-muted-foreground/30"
                      }`}
                    >
                      <span
                        className={`absolute top-0.5 w-4 h-4 rounded-full bg-white shadow-sm transition-transform ${
                          config.enabled ? "left-[22px]" : "left-0.5"
                        }`}
                      />
                    </button>

                    {/* Day name */}
                    <span className={`text-sm font-medium w-24 capitalize ${
                      config.enabled ? "text-foreground" : "text-muted-foreground"
                    }`}>
                      {DAY_NAMES[i]}day
                    </span>

                    {/* Time inputs */}
                    {config.enabled ? (
                      <div className="flex items-center gap-2 ml-auto">
                        <input
                          type="time"
                          value={config.start}
                          onChange={(e) => updateAvailability(day, "start", e.target.value)}
                          className="text-sm px-2 py-1 rounded-md border border-border bg-background focus:outline-none focus:ring-1 focus:ring-primary/20"
                        />
                        <span className="text-muted-foreground text-sm">to</span>
                        <input
                          type="time"
                          value={config.end}
                          onChange={(e) => updateAvailability(day, "end", e.target.value)}
                          className="text-sm px-2 py-1 rounded-md border border-border bg-background focus:outline-none focus:ring-1 focus:ring-primary/20"
                        />
                      </div>
                    ) : (
                      <span className="text-xs text-muted-foreground ml-auto">Off</span>
                    )}
                  </div>
                );
              })}
            </div>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}

// --- Week View ---

function WeekView({
  days,
  todayStr,
  itemsByDate,
  selectedDate,
  onSelectDate,
  loading,
}: {
  days: Date[];
  todayStr: string;
  itemsByDate: Record<string, ActionItem[]>;
  selectedDate: string | null;
  onSelectDate: (date: string) => void;
  loading: boolean;
}) {
  return (
    <div className="grid grid-cols-7 gap-2">
      {/* Day headers */}
      {DAY_NAMES.map((name) => (
        <div key={name} className="text-center text-xs font-medium text-muted-foreground py-2">
          {name}
        </div>
      ))}
      {/* Day cells */}
      {days.map((day) => {
        const dateStr = toDateStr(day);
        const isToday = dateStr === todayStr;
        const isSelected = dateStr === selectedDate;
        const dayItems = itemsByDate[dateStr] ?? [];

        return (
          <div
            key={dateStr}
            onClick={() => onSelectDate(dateStr)}
            className={`group rounded-xl border p-3 min-h-[140px] cursor-pointer transition-all ${
              isSelected
                ? "border-primary bg-primary/5 shadow-md"
                : isToday
                ? "border-primary/40 bg-primary/5"
                : "border-border bg-card hover:border-primary/30 hover:shadow-sm"
            }`}
          >
            <div className="flex items-center justify-between mb-2">
              <span
                className={`text-sm font-semibold ${
                  isToday
                    ? "text-primary"
                    : "text-foreground"
                }`}
              >
                {day.getDate()}
              </span>
              <div className="flex items-center gap-1">
                {dayItems.length > 0 && (
                  <>
                    <button
                      onClick={(e) => {
                        e.stopPropagation();
                        window.open(`/api/calendar/ics?date=${dateStr}`, "_blank");
                      }}
                      className="opacity-0 group-hover:opacity-100 p-0.5 rounded text-muted-foreground hover:text-primary transition-all"
                      title="Download .ics for this day"
                    >
                      <svg className="w-3 h-3" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                        <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16v1a3 3 0 003 3h10a3 3 0 003-3v-1m-4-4l-4 4m0 0l-4-4m4 4V4" />
                      </svg>
                    </button>
                    <span className="text-[10px] font-medium text-muted-foreground bg-muted px-1.5 py-0.5 rounded-full">
                      {dayItems.length}
                    </span>
                  </>
                )}
              </div>
            </div>
            {loading ? (
              <div className="space-y-1.5">
                <div className="h-5 rounded bg-muted animate-pulse" />
                <div className="h-5 rounded bg-muted animate-pulse w-3/4" />
              </div>
            ) : (
              <div className="space-y-1">
                {dayItems.slice(0, 4).map((item) => {
                  const dc = DIFFICULTY_COLORS[item.difficulty] || DIFFICULTY_COLORS.easy;
                  return (
                    <div
                      key={item.id}
                      className={`flex items-center gap-1.5 px-2 py-1 rounded-md text-[11px] ${dc.bg} ${dc.text} ${
                        item.completed ? "opacity-50 line-through" : ""
                      }`}
                    >
                      <span className={`w-1.5 h-1.5 rounded-full shrink-0 ${dc.dot}`} />
                      {item.scheduled_time && (
                        <span className="text-[9px] opacity-70 shrink-0">
                          {formatTime12h(item.scheduled_time)}
                        </span>
                      )}
                      <span className="truncate">{item.title}</span>
                    </div>
                  );
                })}
                {dayItems.length > 4 && (
                  <p className="text-[10px] text-muted-foreground pl-1">
                    +{dayItems.length - 4} more
                  </p>
                )}
              </div>
            )}
          </div>
        );
      })}
    </div>
  );
}

// --- Month View ---

function MonthView({
  days,
  anchor,
  todayStr,
  itemsByDate,
  selectedDate,
  onSelectDate,
}: {
  days: Date[];
  anchor: Date;
  todayStr: string;
  itemsByDate: Record<string, ActionItem[]>;
  selectedDate: string | null;
  onSelectDate: (date: string) => void;
}) {
  const currentMonth = anchor.getMonth();

  return (
    <div className="grid grid-cols-7 gap-1">
      {/* Day headers */}
      {DAY_NAMES.map((name) => (
        <div key={name} className="text-center text-xs font-medium text-muted-foreground py-2">
          {name}
        </div>
      ))}
      {/* Day cells */}
      {days.map((day) => {
        const dateStr = toDateStr(day);
        const isToday = dateStr === todayStr;
        const isSelected = dateStr === selectedDate;
        const isCurrentMonth = day.getMonth() === currentMonth;
        const dayItems = itemsByDate[dateStr] ?? [];

        return (
          <div
            key={dateStr}
            onClick={() => onSelectDate(dateStr)}
            className={`rounded-lg border p-2 min-h-[90px] cursor-pointer transition-all ${
              !isCurrentMonth ? "opacity-40 " : ""
            }${
              isSelected
                ? "border-primary bg-primary/5 shadow-md"
                : isToday
                ? "border-primary/40 bg-primary/5"
                : "border-border/50 bg-card hover:border-primary/30"
            }`}
          >
            <span
              className={`text-xs font-medium ${
                isToday ? "text-primary" : isCurrentMonth ? "text-foreground" : "text-muted-foreground"
              }`}
            >
              {day.getDate()}
            </span>
            <div className="mt-1 space-y-0.5">
              {dayItems.slice(0, 3).map((item) => {
                const dc = DIFFICULTY_COLORS[item.difficulty] || DIFFICULTY_COLORS.easy;
                return (
                  <div
                    key={item.id}
                    className={`flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] ${dc.bg} ${dc.text} ${
                      item.completed ? "opacity-50 line-through" : ""
                    }`}
                  >
                    <span className={`w-1 h-1 rounded-full shrink-0 ${dc.dot}`} />
                    <span className="truncate">{item.title}</span>
                  </div>
                );
              })}
              {dayItems.length > 3 && (
                <p className="text-[9px] text-muted-foreground pl-1">
                  +{dayItems.length - 3} more
                </p>
              )}
            </div>
          </div>
        );
      })}
    </div>
  );
}

// --- Day Detail Panel ---

function DayDetail({
  date,
  items,
  onClose,
  onToggleComplete,
  onReschedule,
}: {
  date: string;
  items: ActionItem[];
  onClose: () => void;
  onToggleComplete: (id: number, completed: boolean) => void;
  onReschedule: (id: number, date: string | null, time?: string | null) => void;
}) {
  const d = new Date(date + "T00:00:00");
  const label = d.toLocaleDateString("en-US", {
    weekday: "long",
    month: "long",
    day: "numeric",
  });

  const completedCount = items.filter((i) => i.completed).length;

  return (
    <Card className="w-80 shrink-0 border-border bg-card self-start sticky top-8">
      <CardContent className="p-4">
        <div className="flex items-center justify-between mb-4">
          <div>
            <h3 className="text-sm font-semibold">{label}</h3>
            <p className="text-xs text-muted-foreground">
              {items.length} {items.length === 1 ? "item" : "items"}
              {completedCount > 0 && ` (${completedCount} done)`}
            </p>
          </div>
          <button
            onClick={onClose}
            className="p-1 rounded-md text-muted-foreground hover:text-foreground hover:bg-muted transition-colors"
          >
            <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        </div>

        {items.length === 0 ? (
          <p className="text-sm text-muted-foreground text-center py-6">
            No items scheduled for this day
          </p>
        ) : (
          <div className="space-y-2">
            {items.map((item) => {
              const dc = DIFFICULTY_COLORS[item.difficulty] || DIFFICULTY_COLORS.easy;
              return (
                <div
                  key={item.id}
                  className={`rounded-lg border border-border p-3 transition-all ${
                    item.completed ? "opacity-60" : ""
                  }`}
                >
                  <div className="flex items-start gap-2">
                    <button
                      onClick={() => onToggleComplete(item.id, !item.completed)}
                      className={`shrink-0 mt-0.5 w-4 h-4 rounded border-2 flex items-center justify-center transition-colors ${
                        item.completed
                          ? "bg-primary border-primary"
                          : "border-border hover:border-primary/50"
                      }`}
                    >
                      {item.completed ? (
                        <svg className="w-2.5 h-2.5 text-primary-foreground" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={3} d="M5 13l4 4L19 7" />
                        </svg>
                      ) : null}
                    </button>
                    <div className="min-w-0 flex-1">
                      {/* Time display */}
                      {item.scheduled_time && (
                        <p className="text-[10px] font-medium text-primary mb-0.5">
                          {formatTime12h(item.scheduled_time)}
                        </p>
                      )}
                      <p className={`text-sm font-medium leading-snug ${item.completed ? "line-through" : ""}`}>
                        {item.title}
                      </p>
                      {item.description && (
                        <p className="text-xs text-muted-foreground mt-1 line-clamp-2">
                          {item.description}
                        </p>
                      )}
                      <div className="flex items-center gap-2 mt-2">
                        <span className={`inline-flex items-center gap-1 px-1.5 py-0.5 rounded text-[10px] font-medium ${dc.bg} ${dc.text}`}>
                          <span className={`w-1.5 h-1.5 rounded-full ${dc.dot}`} />
                          {item.difficulty}
                        </span>
                        {item.topic && (
                          <span className="text-[10px] text-muted-foreground bg-muted px-1.5 py-0.5 rounded">
                            {item.topic}
                          </span>
                        )}
                      </div>
                      {item.filename && (
                        <p className="text-[10px] text-muted-foreground/60 mt-1.5 truncate">
                          {item.source_type === "youtube" ? "\u25B6 " : ""}{item.filename}
                        </p>
                      )}
                    </div>
                  </div>
                  {/* Reschedule + Calendar export */}
                  <div className="flex items-center gap-1.5 mt-2 pt-2 border-t border-border">
                    <button
                      onClick={() => onReschedule(item.id, null)}
                      className="text-[10px] text-muted-foreground hover:text-foreground transition-colors"
                    >
                      Unschedule
                    </button>
                    <span className="text-muted-foreground/30">|</span>
                    <RescheduleInput
                      currentDate={date}
                      currentTime={item.scheduled_time ?? undefined}
                      onReschedule={(newDate, newTime) => onReschedule(item.id, newDate, newTime)}
                    />
                    <div className="ml-auto">
                      <ItemCalendarActions item={item} />
                    </div>
                  </div>
                </div>
              );
            })}
          </div>
        )}
      </CardContent>
    </Card>
  );
}

function RescheduleInput({
  currentDate,
  currentTime,
  onReschedule,
}: {
  currentDate: string;
  currentTime?: string;
  onReschedule: (date: string, time?: string) => void;
}) {
  const [editing, setEditing] = useState(false);
  const [newDate, setNewDate] = useState(currentDate);
  const [newTime, setNewTime] = useState(currentTime ?? "");

  if (!editing) {
    return (
      <button
        onClick={() => setEditing(true)}
        className="text-[10px] text-muted-foreground hover:text-foreground transition-colors"
      >
        Move to...
      </button>
    );
  }

  const handleConfirm = () => {
    if (newDate) {
      onReschedule(newDate, newTime || undefined);
      setEditing(false);
    }
  };

  return (
    <div className="flex items-center gap-1">
      <input
        type="date"
        value={newDate}
        autoFocus
        onChange={(e) => setNewDate(e.target.value)}
        className="text-[10px] px-1.5 py-0.5 rounded border border-border bg-background focus:outline-none focus:ring-1 focus:ring-primary/20"
      />
      <input
        type="time"
        value={newTime}
        onChange={(e) => setNewTime(e.target.value)}
        className="text-[10px] px-1.5 py-0.5 rounded border border-border bg-background focus:outline-none focus:ring-1 focus:ring-primary/20 w-20"
      />
      <button
        onClick={handleConfirm}
        className="text-[10px] text-primary hover:text-primary/80 font-medium transition-colors"
      >
        OK
      </button>
      <button
        onClick={() => setEditing(false)}
        className="text-[10px] text-muted-foreground hover:text-foreground transition-colors"
      >
        Cancel
      </button>
    </div>
  );
}
